---
mole_volume_dir: /var/local/lib/mole
mole_state: started
mole_config_dir: '{{ lookup("env", "XDG_CONFIG_HOME") | default(lookup("env", "HOME") + "/.config", true) }}/mole'
mole_pull_image: no
mole_dockerpy_state: present
mole_listen_ip: 127.0.0.1
mole_docker_api_version: auto
mole_docker_image_tag: latest
